version: "2"
services:
  app:
    image: registry.gitlab.com/deepset-ai/open-source/fasttext-embeddings-de
    build: .
    command: bash -c "cd /home/docker/code/ && ./train_fasttext.sh"
    network_mode: "bridge"
    container_name: "fasttext"
    environment:
      # ** INPUT / OUTPUT DATA **
      CORPUS: input/wiki.de.txt
      CORPUS_TYPE: wiki
      #For CORPUS_TYPE= "wiki", you have two options. Either supply the wiki dump as a mounted file OR download it by
      # specifying the options in the next lines
      DOWNLOAD_WIKI: "true" # "true" # cannot supply boolean with docker compose
      # name of the wiki dump file to download
      WIKI_DUMP: dewiki-latest-pages-articles.xml.bz2
      # URL of the wiki dump (Download will use concatenated string of WIKI_PREFIX and WIKI_DUMP
      WIKI_PREFIX: https://dumps.wikimedia.org/dewiki/latest/
      OUTPUTDIR: output
      # ** MODEL PARAMETERS **
      # Min occurences of a token to be considered in the model vocab
      VOCAB_MIN_COUNT: 10
      # Dimensionality of word embedding
      VECTOR_SIZE: 300
      # Maximum number of training iterations (= epochs)
      MAX_ITER: 50
      # Number of words considered as a "local context" into both directions of the current target word
      # fasttext with skipgram implementation will predict a word out of this window using the "target" word
      WINDOW_SIZE: 5
      MAX_NGRAM_WORD: 1
      MAX_NGRAM_CHAR: 8
      MIN_NGRAM_CHAR: 3
      N_BUCKETS: 2000000
      SAMPLING_THRESH: 0.0001
      LEARNING_RATE: 0.05
      # ** RUNTIME SETTINGS**
      # Verbosity of logging (only increase for debugging)
      VERBOSE: 3
      THREADS: 16
      # ** META INFORMATION **
      #(will be stored after training in "word_emb.meta" file. Useful for inspecting, comparing and deploying models)
      TEXT_TYPE: "wiki"
      TOKEN_SPACER: "none"
      META_NOTES: "nothing"
    volumes:
        - ../data/input:/home/docker/code/input
        - ../data/output:/home/docker/code/output
