version: "2"
services:
  app:
    image: registry.gitlab.com/deepset-ai/open-source/fasttext-embeddings-de
    build: .
    command: bash -c "cd /home/docker/code/ && ./train_fasttext.sh"
    network_mode: "bridge"
    container_name: "glove"
    environment:
      CORPUS: input/wiki.de.txt
      CORPUS_TYPE: wiki
      WIKI_DUMP: dewiki-latest-pages-articles.xml.bz2
      WIKI_PREFIX: https://dumps.wikimedia.org/dewiki/latest/
      OUTPUTDIR: output
      VERBOSE: 2
      VOCAB_MIN_COUNT: 10
      VECTOR_SIZE: 100
      MAX_ITER: 10
      THREADS: 8
      WINDOW_SIZE: 5
      MAX_NGRAM_WORD: 1
      MAX_NGRAM_CHAR: 0
      MIN_NGRAM_CHAR: 0
      N_BUCKETS: 2000000
      SAMPLING_THRESH: 0.0001
      LEARNING_RATE: 0.1
    volumes:
      - ../custom-embeddings/data/corpus:/home/docker/code/input
      - ../custom-embeddings/data/embeddings/word2vec:/home/docker/code/output
